from flask import Flask, render_template, request, jsonify
import json
import random
import os

app = Flask(__name__)

# Define emotions and chits
emotions = {
    "happy": {
        "display": "Open Me When You’re Happy",
        "color": "#FFEB3B",
        "chits": [
            "Just like our Wonderla Recoil ride, my heart skips and thrills every time you hold my hand!",
            "Our train memories on the way to Bangalore? Pure magic! I could relive that morning lap-sleep forever!",
            "The way you cutely packed our bags on the return bus from Wonderla… happiest travel memory of my life!",
            "Eating samosa channa with you outside Fresh Today was simple, but it felt like a 5-star dinner because you were there!",
            "That lip kiss in the lift? My heart still races thinking about how unplanned yet perfect it was!",
            "Watching Jersey together in the library and sharing our first lip lock! Happiness redefined!",
            "Every scooty ride with you feels like a Mani Ratnam montage with an AR Rahman score in the background!",
            "The ISKCON temple visit with you gave me a peace and happiness I never thought possible!",
            "Wonderla wave pool + us dancing in the rain = happiest water moments of my life!",
            "Your hugs at the bus stop after Wonderla still warm my heart every time I think about them!",
            "When you picked me up to go eyeliner shopping at City Center! Cuteness overload! Simple things with you feel huge!",
            "Our concert night waiting for Shakthisree to perform! Happiness in waiting itself because you were beside me!",
            "Long rides with you are my therapy sessions, my joy rides, my everything!",
            "Sharing momos outside the Bangalore bus stand with you? Happiest street food ever!",
            "Watching “Thug Life” with you at Sangam was special because your giggles made the whole theatre feel like ours!",
            "Dropping me at the station after cute rides home! Happiest goodbyes that always make me want more time!",
            "Cuddling you in the bus on the way back from Bangalore = happiness wrapped in warmth!",
            "Helping you fill those Google Sheets on GMeet? I was smiling like an idiot the whole time because it was us, together!",
            "Designing the Kalpavrikshalaya logo with you gave me so much happiness! Our creativity and love blending together!",
            "That first ever “Heart” you sent in the morning? Happiest shock of my life!",
            "Our game of Skribbl that night made me laugh so much! Happiness is being silly with you!",
            "When you hugged me after beating me for the “Mind Palace” line! happiest solution to a fight ever!",
            "The day we went to Aishwarya Stores, SB, and City Center together! Happiest errand-running I’ve ever done!",
            "Your cute admiration during my auctioneering dry run still makes me blush with happiness!",
            "The time you sighted me while I was working! Happiness is being your “secret view”!",
            "Wonderla lazy river ride with you = pure floating happiness!",
            "Watching you enjoy your biriyani at Dindugal Thalapakatti = my happiest foodie sight ever!",
            "Your favorite Manamaganin Sathiyam song makes me think of us every single time! Happiest melody in my head!",
            "Every time you wear black or blue, I feel like the happiest, luckiest guy to walk beside you!",
            "That little moment under the tree near OAT during Instincts? Happiest kind of quietness ever!",
            "Watching Jersey together in the auto ride back home! Happiest multitasking ride of my life!",
            "Seeing your joy when you tried the dark chocolate I gave you = sweetest happiness!",
            "Every photo we clicked together before temples, or random outings = happiness frozen in time!",
            "The night when you gave me the biggest surprise by saying “Indha Unnoda Chance” Happiest moment of my entire life!",
            "Happiness was hearing you say “You make me feel special” on May 10! Etched forever in my heart!",
            "Our very first time at the beach together! Happiest salty breeze and sandy toes!",
            "Eating bhuva with your mom’s gravy is your comfort but watching you happy while eating is mine!",
            "The giggles during our ride home after a fight! Happiest proof that nothing can break us!",
            "Rain dance at Wonderla with you = happiest carefree laughter!",
            "Our car ride in Bangalore with me on your lap = happiest car journey ever!",
            "Happiness was when you quietly waited while I finished my practice at college! Patience that melted me!",
            "Every playful fight we’ve had always ends in hugs and kisses! Happiest cycle ever!",
            "Watching “3” with you will be happiness beyond measure, because it’ll be our memory now!",
            "Our selfies before rides, after fights, during movies, and random moments = happiest little album of us!",
            "Your smile is literally my happiest addiction!",
            "Happiness is when you forget the world and hold me tight in an auto or bus!",
            "Happiness is every time you call me when you leave college! That “on the way” call is my favourite ringtone!",
            "Watching your eyes light up in ISKCON while we prayed together = Happiest soul moment!",
            "Happiness is when you drop me at the station with a kiss surprise!",
            "The night we stayed up editing the logo and laughing at our struggles = Happiest kind of tiredness!",
            "Your face after riding Recoil at Wonderla! Happiness of seeing you overcome fear and scream with joy!",
            "The happiness of being your plus one to every temple, theatre, or café! I’ll never get enough of it!",
            "Happiness is when you prioritize me even in small, silly ways!",
            "That 3 Consecutive days where we roamed half the city! Happiest drive of my life!",
            "When you admired me during auctioneering practice = Happiest proud moment of my life!",
            "Happiness is knowing your dream of Paris & Iceland! Because one day I’ll see you happiest there!",
            "Wonderla main pool time when it was just us! Happiest splashy romance!",
            "Happiness is when you reassure me with a hug after a fight!",
            "Above all, happiness is simplet’s me and you, Swetha, in every moment we’ve lived and every memory we’ll create!"
        ]
    },
    "sad": {
        "display": "Open Me When You’re Sad",
        "color": "#4CAF50",
        "chits": [
            "Remember the first time we spoke after a year? That smile on your face that day could chase away every sadness in the world. Including this one!",
            "You once told me I make you feel special. Let me remind you, that’s my favorite job in the world!",
            "Sadness might be here now, but so am I. And I’m not leaving until you’re smiling again!",
            "Remember our first café visit? We were so clueless, yet it turned out to be the start of something beautiful. This sadness will lead to something beautiful too!",
            "Think about the bouquet you gave me on Feb 19. That moment changed my life! Sadness can’t erase that magic!",
            "Remember the day you were limping and I broke my silence to ask if you were okay? I’ll always break any wall to reach you!",
            "This sadness is nothing compared to how brave you were when you chose to trust me again after a whole year!",
            "When I close my eyes, I see you smiling in Wonderla after that crazy ride. Hold onto that joy, da!",
            "Next time we meet, I’ll buy you a Kinder Joy and we’ll laugh at the toy until we forget the reason you were sad!",
            "You once fought me just to stay in my life. That strength will chase away any sadness too!",
            "Think of us sitting at the beach in silence. No words needed, just peace, just love!",
            "If sadness makes you cry, imagine me wiping your tears and calling you my golden fish until you giggle!",
            "Remember how we fought and didn’t speak for a while but still came back stronger? This sad moment will pass just like that fight did!",
            "You once told me you’d fight the world for me. You can fight this sadness too!",
            "Remember the day you let me hold your hand for the first time? My heart still races thinking of it. Let that memory beat the sadness!",
            "When sadness feels heavy, think about our first lip lock! Magical, soft, and unforgettable!",
            "You once fixed my hair so carefully with your scrunchie. Imagine that moment again, soft and calm, letting your sadness melt away!",
            "Sadness doesn’t stand a chance against the girl who made me smile even on my worst day!",
            "Remember when you won our first arm wrestling match and laughed like a kid? Let that laughter fill your heart now!",
            "This sadness is just a passing cloud. Your smile is the permanent sunrise I wait for every day!",
            "Remember the time we stayed up late just talking? I’d stay awake a thousand nights just to make sure you never feel alone!",
            "You once told me you’d never completely leave my life. I’ll never let sadness take you away from me either!",
            "Picture the moment you saw me outside your college and lit up instantly. That joy is still yours!", 
            "Sadness can’t last when you think of our first forehead kiss. Safe, warm, and full of love!",
            "Remember the day you teased me for overthinking everything? Well, stop overthinking and smile for me now!",
            "This sad day is nothing compared to the happiness waiting for us at our next Friday movie night!",
            "Remember the day I said sorry after a year of silence? That was the start of something beautiful. Sadness will just be another chapter we’ll smile at later!",
            "You once told me I make you feel safe. So let me be your safe place now, no sadness allowed!",
            "Sadness might feel huge now, but so did our fights. And look, we overcame them all!",
            "Remember the day you told me about your breakup? I promised I wouldn’t leave. And I’m still keeping that promise, even on sad days!",
            "When sadness knocks, just imagine us eating biriyani together and laughing over the spice level!",
            "You once said I remind you of someone who used to care. I’m here to remind you that I’ll never stop caring for you!",
            "Remember how we survived dance mam’s long lectures just to spend time together? We can survive this sadness too!",
            "The day you called me just to say you missed me is proof that distance or sadness can never win against us!",
            "Sadness might make today feel long, but our next date will make it all worth it!",
            "Remember our first group outing after a year of silence? That day brought us back together. This sadness will bring us closer too!",
            "Think of the way you called me your Husband the 1st time. I promise I’ll always protect your smile!",
            "Sadness may feel heavy, but we’ve carried heavier. Like all those fights we had. And still made it here, stronger!",
            "Remember how happy you were when we clicked our first picture together on Feb 19? Let that happiness return now!",
            "This sadness will pass, but the memory of you bringing me that bouquet will stay forever!",
            "You once trusted me with your secrets. Trust me again now, when I say this sadness won’t last!",
            "Remember our first bike ride after Feb 19? The air, the freedom, the laughter. Feel that freedom again and let sadness go!",
            "Even on days we fought, I never stopped loving you. So today, I’ll love you enough for both of us until you smile again!",
            "Remember how you said yes to my proposal despite all your fears? That bravery is still in you!",
            "This sadness might feel like a storm. But you’ve always been my rainbow after every storm!",
            "Remember how we laughed at the silliest things at Fusilli Reasons? Let that laughter echo in your heart now!",
            "Sadness can’t touch you when you think of our first proper hug. The one we both secretly waited for!",
            "You once told me I was your safe space. So here’s your reminder: I’ll hold that space for you forever!",
            "When sadness feels loud, put on our playlist and let Rahman’s music calm your heart. Just like I always do!",
            "Remember the time you almost got caught trying to bunk college but still met me later? That dedication can defeat any sad day!",
            "This sadness is just another test. And you’ve always been the girl who passes every test with grace!",
            "Think about the way we reconnected after so long. Sadness can never truly break what we’ve built!",
            "Remember how you touched my heart by forgiving me after a year? Forgive this day too and let happiness back in!",
            "When sadness makes you doubt yourself, just remember! You are the girl who made me believe in love again!",
            "Remember that first time we sat together in silence, just holding hands? Silence can be healing. Let it be now!",
            "This sad day is temporary, but our story is forever. And forever always has happy chapters!",
            "Picture us going to Wonderla again, me screaming my lungs out on the rides while you laugh at me! See? You’re smiling already!",
            "Remember the first time I called you “My Princess” and you blushed? That moment is stronger than any sadness!",
            "You once said I make you feel special! So let me remind you again, you are my everything!",
            "This sadness is just another page. But our story ends with you smiling, always!"
        ]
    },
    "stress": {
        "display": "Open Me When You’re Feeling Stressed",
        "color": "#9C27B0",
        "chits": [
            "Stress might feel like that endless KRK sir lecture! But just like then, you’ll walk out smiling when it’s done!",
            "Remember our first long bike ride when we went to Hindustan? Let the wind in your hair calm your mind just like that day did!",
            "Think of the time you spoke to me on train when I was on my Vizag Trip! Even stress would laugh if it saw that incident!",
            "When life feels too loud, dance it out the way you do when your favourite song plays!",
            "Picture us sitting at the beach, waves crashing, my hand in yours! Nothing else matters!",
            "When worries pile up, imagine me cheering for you like I do when you dance! You’re my star performer always!",
            "Remember how we were before our first Beachville Cafe meet? But look how beautifully that day turned out!",
            "Next time stress hits, imagine me dramatically losing an arm wrestling match just like I did in EA the day before our wonderla trip, just to see you grin again!",
            "Stress is temporary! But that day you wore my Brown Shirt? Eternal comfort right there!",
            "Life might feel like a viva now! But you’ve got all the answers, my topper girl!",
            "Whenever you feel burdened, think of me saying, “Relax, di! We’ve got this together!”",
            "Remember the night we sat talking until 6 AM? That safe space is still here, always!",
            "If today feels heavy, think about the time we danced in wonderla! See? You’re already smiling!",
            "Stress can never beat the memory of you calling me at midnight just to tell me you miss me!",
            "Remember our first fight and how we came back stronger? This too will pass and make you stronger!",
            "Next time stress makes you cry, just imagine me buying you a Kinder Joy and sitting beside you till you laugh!",
            "If life feels like a traffic jam, remember how patient you were when I sometimes come late to pick you up! You’ve got patience to handle this too!",
            "When stress builds up, remember the way you proudly introduced me to your friends as your boyfriend! Nothing else matters then!",
            "Life might feel stormy now! But you’ve always been my sunshine after every fight!",
            "Stress is no match for that fierce look you give me whenever I do something stupid!",
            "Remember when you wore that red dress I loved? That moment made my whole week light up! You can light up this week too!",
            "If stress is a puzzle, think of me as your missing piece! Together, we always make sense!",
            "When things feel out of control, remember the day I confessed my love! Neither of us saw that coming, but it was beautiful!",
            "Stress can’t survive the image of us laughing over the silly things that we do in our day-to-day life!",
            "If you’re feeling tired, remember the day you bunked class just to be with me! That boldness is still in you!",
            "Close your eyes and picture our first bath! Happiness was literally on our faces!",
            "Life can be tough! But you’ve handled worse, like surviving that endless KK’s Period every day!",
            "Imagine us having biriyani together again! Spicy, messy, and full of love, just like us!",
            "Stress is just background noise! Remember our first playlist together? Focus on that music instead!",
            "Remember the look on my face when you said yes to giving me a chance! That joy is still here for you to feel!",
            "If stress was a teacher, just imagine me distracting you in class again! Suddenly not that scary, right?",
            "Life might feel like a bad day! But you turned my worst days into my best ones just by texting “Hi!”",
            "Next time you feel low, imagine me dramatically begging you for another chance to make up for the mistakes I did!",
            "Stress might try to make you doubt yourself! But I’ve seen you stand up for what you love! That courage is unshakable!",
            "Remember how you made me wait outside your college just to talk for 5 minutes? You’ve got the strength to make time for what matters!",
            "Stress can’t win when your favourite mutton biriyani exists! Let’s go have some soon!",
            "Imagine us watching a dumb movie and laughing at the most serious scenes! That’s our magic against any tension!",
            "Think about the day we met after a year of silence! If we can fix that, we can fix anything!",
            "Life might feel heavy, but you’re still the same girl who stood up to your fears and trusted me again!",
            "Remember how excited you were when we got our first good picture together? That smile is still my favourite cure!",
            "Stress might feel like a moment a dancer’s anklet breaks right before her Salanga pooja or arangetram! But what matters is how strong her mindset is and how good of a comeback she’s gonna give for her setback!",
            "When life feels too fast, imagine us slow dancing under the stars! Just us, no rush!",
            "Think about the first time we held hands in public! Bold, fearless, and so proud of us!",
            "If today feels harsh, remember the way you teased me by tickling me every time we meet!",
            "Life may be unpredictable, but so was the day you showed up with that bouquet! And look what it led to!",
            "Remember the first beach visit where you just sat quietly with me? Let that calmness wash over you now!",
            "If stress tries to scare you, just imagine me showing up with your favourite ice cream and refusing to leave until you smile!",
            "Life might feel blurry but remember the way you looked into my eyes that day at the café! Everything was clear then!",
            "Imagine me holding your scrunchie hostage until you laugh! Yes, I would actually do that!",
            "Remember that night you shared your fears with me for the first time? You can share this stress with me too!",
            "Stress is just a short chapter! But our love story? That’s the whole book!",
            "Think of the way you encouraged me when I was low! Let me be your cheerleader now!",
            "When life feels overwhelming, remember the way you whispered “I trust you” That trust can hold you up too!",
            "If stress makes you doubt us, just look back at how far we’ve come! Every fight, every tear, every win led us here!",
            "Picture our next Friday night! Popcorn, silly arguments, and your head on my shoulder!",
            "Remember the way we clicked that first perfect photo at EA? Imagine us clicking away all your worries like that!",
            "Stress might scream at you, but I’ll always be the louder voice saying “I love you!”",
            "Think about the time you helped me fix my hair! That simple, soft moment is all you need to breathe again!",
            "Life can be hard, but you’ve always been my reason to smile! Let me be yours today!",
            "Stress fades, love stays! And my love for you? Only grows stronger every single day!"
        ]
    },
    "angry_mistake": {
        "display": "Open Me When You're Angry Because I Made a Mistake",
        "color": "#FF9800",
        "chits": [
            "I messed up di! Let me start making up by replaying our first forehead-kiss moment for you, slowly!",
            "I’m sorry!  Trade me one angry minute for one huge hug when we meet!",
            "I know I hurt you! Let me earn back your smile with a Kinder Joy surprise and a goofy dance!",
            "I’ll fix this. I’ll stop defending, start listening your words first, always!",
            "I’m sorry. Let me take responsibility and treat you to your favourite Dindugal biriyani this week!",
            "I know you’re angry, and that’s fair! Let me bring you the exact snack that always makes you grin!",
            "I’ll be the calm after your storm! Promise a forehead kiss every time I forget to be gentle!",
            "I messed up! Can I repay you with a small movie night of only your picks and no arguments?",
            "I’m sorry di! I’ll spend the next hour sending you only things that made you smile at Wonderla!",
            "I hear you and I’ll stop now and explain later when you want!",
            "I know I blew it! Let me write one silly poem about how dumb I was and read it to you!",
            "I’m ready to make this right! I’ll say sorry in every language you like until you laugh!",
            "I messed up. Let me be the one who apologises and give you the space you asked for!",
            "I’ll make a deal! My phone off for the evening and my full attention on you when you want to talk!",
            "I hurt you, and that’s on me! Let me fix one small thing today to start healing",
            "I’m sorry! Can I replace this anger with a silly memory of us pushing the scooty together?",
            "I’ll be accountable! Tell me one thing I can change now and I’ll start immediately!",
            "I know you’re angry! I’ll bring you your favourite Watermelon juice and sit quiet while you cool down!",
            "I messed up! Consider this chit my handwritten apology that I’ll actually act on!",
            "I know words aren’t enough! I’ll show you by doing the little things you asked me to!",
            "I was wrong! Let me earn back trust by doing that chore you hate for a whole week!",
            "I made a mistake! Forgive me after I perform the worst, most dramatic sorry-dance for you!",
            "I’m sorry di! When you’re ready, let me take you to the temple and offer a tiny prayer for us!",
            "I’ll stop arguing and start apologising! Tell me how you want me to make amends!",
            "I messed up! I’ll keep a count of hugs until you stop being mad, starting with five extra today!",
            "I’m sorry! Let me turn this into a small ritual! One coin, one promise, one step forward!",
            "I know I hurt you! Let me be patient while you process! I’ll wait and be better!",
            "I was careless! I’ll undo it with consistent small actions, not big empty words!",
            "I’ll be better! I’ll let you speak first the next three times we fight!",
            "I know you’re angry, and you should be! I’ll show you I’ve learned by changing one habit you mentioned!",
            "I’m sorry! If you want distance now, I’ll give it! If you want talk, I’ll listen without defence!",
            "I messed up! I’ll plan a quiet temple ride so we can both breathe and reset!",
            "I’m sorry di! Today I’ll be the one to apologise through actions!",
            "I know this hurts! Let me be the one who apologises until you can hear me again!",
            "I was wrong! Let me show it by carrying your bag, holding your hand, and saying sorry!",
            "I hurt you! I’ll stop making jokes and start making changes!",
            "I’m sorry! Let my next message be just three things I’ll change, no excuses!",
            "I was thoughtless! I’ll earn back your trust with small daily proofs, starting tomorrow!",
            "I know you’re mad! I’ll be quiet, but I’ll also do one nice thing before you wake up!",
            "I made a mistake! I’ll fix it slowly, like counting our hug-tally back to happiness!",
            "I’m sorry di! Let me prove it: I’ll show up early for you this week, no delays!",
            "I messed up! Please allow me to apologise in person, with a forehead kiss and full attention!",
            "I hurt you! I’ll write down what I learned so I don’t repeat it, and I’ll share it when you want!",
            "I’m sorry! Can I be punished by watching your favourite movie with popcorn made your way?",
            "I know I failed you! Let me start small: one thoughtful gesture per day for the next week!",
            "I made a mistake! I’ll stop defending and start repairing, step by step!",
            "I’m sorry! I’ll let you set the terms for making up and I’ll follow them!",
            "I messed up, and I’m ashamed! Let me carry this humbly and rebuild what I broke!",
            "I’m sorry di! I’ll bring you the charm you liked and say sorry with every little detail right!",
            "I hurt you! I’ll be the person who remembers your loves and shows up there consistently!",
            "I messed up! Give me a small mission to complete and I’ll do it perfectly to show I care!",
            "I’m sorry! I’ll create a quiet evening: no calls, no drama, just us repairing slowly!",
            "I made a mistake! I’ll be the one to plan the next small date and follow through, no slip-ups!",
            "I’m sorry di! I’ll stop the behaviour, not just apologise for it. Watch me take action!",
            "I messed up! For every time I hurt you, I’ll do one thing that makes you feel cherished!",
            "I’m sorry! Let me make amends by doing one thing today that removes your stress!",
            "I made a mistake! I’ll be accountable: tell me one boundary and I’ll never cross it again!",
            "I’m sorry di! Whenever you feel ready, I’ll show you how I’ll be different this time!",
            "I messed up! I’ll remind you daily that you matter more than my ego!",
            "I’m sorry! I’ll spend the next week proving my apology with consistent kind acts, starting now!"
        ]
    },
    "angry_fought": {
        "display": "Open Me When We’re Angry Because We Fought",
        "color": "#F44336",
        "chits": [
            "We survived a whole year of not speaking and still found our way back. This fight? Just a passing cloud over a strong sun!",
            "Close your eyes and remember our first forehead kiss. It had no anger, only warmth. That’s still us!",
            "Imagine me holding out a Kinder Joy right now, saying “Peace offering?” Because I would!",
            "The silence after a fight can feel heavy, but ours is never permanent. We always find a way back!",
            "You once skipped college just to meet me. If that’s not stronger than this fight, what is?",
            "Remember our first ECR ride? Wind in your hair, no worries. That’s how I want us to feel again!",
            "You love mutton biriyani, I love feeding you the last bite. How can we stay angry with that memory?",
            "Even AR Rahman songs have tense notes before the melody flows. This fight is just that tense note!",
            "Remember when I copied from your answer sheet? Teamwork started early for us. Let’s team up again now!",
            "We’ve been through bigger storms! This fight is just a drizzle!",
            "Our first lip lock at my college was filled with courage and love. Let that memory melt the anger now!",
            "Even when we fought back then, you still checked on me. That’s our real story!",
            "Your dance practices always made me wait just to watch. I can wait now too until we’re okay again!",
            "Remember feeding each other at Fusilli Reasons? We’ve always shared more than food!",
            "A fight can’t erase the bouquet of Feb 19th! It was the start of us!",
            "Our love isn’t like a straight road! It’s like Chennai’s lanes! Sometimes narrow, but always leading somewhere beautiful!",
            "I know you’re angry! But imagine me fixing your scrunchie again. Wouldn’t you smile?",
            "Even when we had that big year-long gap, you were still in my prayers. This is smaller than that!",
            "Fenix would probably wag his tail now and push us closer, just like always!",
            "You always make me promise “never leave.” Even this fight won’t change that!",
            "We’ve been patient through so much. This moment deserves the same patience!",
            "You love holding hands when walking. Let’s replace this fight with a walk soon!",
            "Remember how we sat on the beach the first day of our chance? The waves didn’t judge, neither should we!",
            "You once called me your Batman. Even Batman fixes his mess. Let me fix this too!",
            "That first café visit, clueless but excited! That’s still us. This fight is just noise!",
            "When we fought with others, we stood by each other. Let’s do that now!",
            "You’re my goddess! And I’m ready to pray my apology until you forgive me!",
            "Even your dance mam’s long speeches didn’t scare me away. This fight won’t either!",
            "Remember the scrunchie moment? Slow, soft, loving! That’s how I want this to end!",
            "Our story is proof that waiting pays off. Let’s wait out this anger together!",
            "You once told me “You make me feel special.” That’s still my mission!",
            "Remember how you boldly confessed your feelings? I’ll boldly apologise until we’re okay!",
            "We’ve seen each other at our weakest. This fight is just another layer to peel back!",
            "Think of our first movie night. Just us, no tension. That’s waiting for us again!",
            "We’re a Mani Ratnam kind of love! Even fights turn into scenes of tenderness later!",
            "Picture me bringing you mutton biriyani now with a sorry note tucked in!",
            "Even when angry, you’d still text me about Nisha or your dad. That’s how deep we run!",
            "You’re the one who taught me patience. I’ll use it now to reach you!",
            "Remember how you used to tease me at school? That teasing was always softer than fights!",
            "I’d rather watch you dance than argue. Let’s swap this fight for a performance!",
            "Kinder Joy always ends with a surprise. Let’s end this fight with one too!",
            "We waited five years to get here. We won’t let a fight push us back!",
            "Picture us sitting on the beach again, wind on our faces, forgetting the world!",
            "We’re stronger than a misunderstanding. We proved it already!",
            "You once said my eyes calm you. Look at them again and see if the fight stays!",
            "Even Wonderla rides ended with laughter, not screams. Let’s end this fight the same way!",
            "We’ve shared secrets, dreams, fears. A fight can’t undo that!",
            "Think of me placing your favourite AR Rahman song now, holding out my hand for a truce!",
            "You love it when I call you “Di.” Let me say it now! “Sorry Di!”",
            "We’re the couple who survived distance and silence. We’ll survive this too!",
            "You once fed me with your hands just because I forgot my spoon. That kindness still lives in us!",
            "Even our big August argument didn’t end us. This fight won’t either!",
            "We’re like a Rahman track! Chaos first, magic later!",
            "Think of our arm wrestling match. You won. Let’s call this fight your win too!",
            "We promised no walking away. I’m still here, waiting!",
            "You loved seeing me nervous before confessing. Right now I’m nervous to lose you again!",
            "Remember the way you looked at me on Feb 19th? That’s stronger than any fight!",
            "Our fights are just rehearsals for stronger comebacks!",
            "Picture our first ride after that one-year silence. That’s the power of us!",
            "I choose you through every fight, every mistake, every mood. Always!"
        ]
    },
    "missing": {
        "display": "Open Me When You’re Missing Me",
        "color": "#03A9F4",
        "chits": [
            "Just like how you danced your heart out that day, dance now too! Feel me in every beat, I’m right there cheering for you!",
            "Kinder Joy in your hand, my smile in your heart! That’s how close I am even when far away!",
            "Mutton biriyani is your comfort food, and I’m your comfort person! Hold on love, I’m with you always!",
            "That first café date we had! From strangers to this! Think of that magic when you miss me!",
            "Wonderla’s water rides! The way you laughed non-stop! Remember that joy, I’m sending it to you now!",
            "When we bunked and just sat talking! That moment is proof we don’t need a crowd, just us!",
            "Just like how you love sunrises at the beach, imagine me sitting with you right now at your favorite spot!",
            "Remember the bouquet I gave you? That day was the start of something we never expected! Feel that warmth!",
            "“Indha unnoda chance” The day you said that changed everything for me! Whenever you miss me, remember I’m still living that moment!",
            "My silver chain, your dancing, my teasing! All still here, waiting for our next day together!",
            "Picture us under the Eiffel Tower! We’re not there yet, but we’re closer every day my love!",
            "Your small limping step at the outing! That’s when I couldn’t stay away! I’m still here, never away!",
            "You love mountains over beaches! Think of our love like that! Steady, tall, unshakable!",
            "Wonderla’s roller coaster! That thrill is our story! Hold on through the highs and lows, I’m with you!",
            "“Through Every Thick & Thin” That’s not just a line, it’s our promise!",
            "Dance now! Every step is a hug from me!",
            "Kinder Joy’s surprise inside is like me! You may not see me now but I’m right there, waiting for you!",
            "That beach evening when you finally opened up to me! Think of that courage, it’s what keeps us together!",
            "Remember my goofy jokes during our rides? Laugh at them now and feel me teasing you again!",
            "Imagine I cooked Your mutton biriyani! Eat it slow and imagine me stealing a bite from your plate!",
            "Our dreams of Paris & Aurora are not just dreams! They’re waiting at the end of this distance!",
            "Feb 19 at DG! I lost the auction but turned into the best day of my life! Hold onto that magic!",
            "The way you held the bouquet that evening! That’s how I hold you in my heart now!",
            "Our marathon run! Step by step, just like now, we’re moving closer!",
            "Your favourite playlist? Play it now! Pretend I’m singing badly next to you!",
            "Remember when you taught me patience without saying a word? That’s why I can wait for you now!",
            "Your first text that morning was dry but ended with magic that night! Missing me now? The magic is still alive!",
            "Wonderla’s rain dance! Your energy, your smile! Feel that vibe and know I’m smiling too!",
            "You’re my “Perfect” just like Ed Sheeran said! Whether here or far, that doesn’t change!",
            "The chain I gave you! Imagine it as my hug around your neck!",
            "Our favorite café corner is empty now, but soon it’ll be full of our laughter again!",
            "Remember how we kept our story hidden at first? Now it’s a story the stars would envy!",
            "Your soft “Hi” after a whole year of silence was the best sound of my life! That’s how strong we are!",
            "Kinder Joy’s small toy! Save one for me! Next time, we’ll build it together!",
            "You never settle for less! Don’t settle for less than our love either!",
            "Remember me waiting outside your college? Imagine me waiting now too, only for you!",
            "You dance like no one’s watching! Imagine I’m watching now, proud, smiling!",
            "Our beach talks! Every wave carried your words! They’re still with me now!",
            "Wonderla’s giant wheel! Our love is like that! Going up and up, never stopping!",
            "That day when you chose to give me a chance! I’m still in awe of that moment!",
            "Your love for biriyani is my love for you! Endless and layered with warmth!",
            "Remember your silly belt disaster? Laugh at that and miss me a little less!",
            "We don’t need a Paris street to make memories! Even these words now are our little Paris!",
            "Our first argument hurt, but it built us too! Even missing me now is building something strong!",
            "You once said I make you feel special! You do the same to me every single day!",
            "That small ride we take when our entire day is about to end! Think of that and smile!",
            "Our dreams of teaching kids to be like us! Think of that future when missing me now!",
            "Kinder Joy’s sweetness! Let that be my kiss to you now!",
            "Wonderla’s queues were long, but we waited! Just like now, waiting for our next day together!",
            "You’re my auctioneer! You own every stage and my heart too!",
            "That moment you limped and I came running! I’ll always come running for you!",
            "Your playlists, my bad singing! That’s still our thing, distance can’t change it!",
            "Biriyani on Sundays, me on every day! That’s how much I’m part of you!",
            "That beach we saw once! Imagine me sitting next to you now, holding your hand!",
            "Wonderla’s laughter echoes even now! Close your eyes and you’ll hear me too!",
            "Our late night Google Meet! Deep talks, small smiles! We’re still just a call away!",
            "Our first real conversation after a year! That’s proof we’re unbreakable!",
            "Kinder Joy’s little surprise is like our future! Small now but magical ahead!",
            "Our dreams of mountains, our dreams of auroras! Hold onto them while I hold onto you!",
            "And when you miss me most, just whisper “InizioDiNoi” Because that’s where it all began for us!"
        ]
    }
}

STATE_FILE = "state.json"

# Initialize or load state with UTF-8 encoding
if os.path.exists(STATE_FILE):
    with open(STATE_FILE, "r", encoding="utf-8") as f:
        state = json.load(f)
else:
    state = {eid: [] for eid in emotions.keys()}
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False)

@app.route("/")
def home():
    return render_template("index.html", emotions=emotions, state=state)

@app.route("/get_chit", methods=["POST"])
def get_chit():
    eid = request.json.get("emotion_id")
    if eid not in emotions:
        return jsonify({"error": "Invalid emotion"}), 400

    available_chits = [c for c in emotions[eid]["chits"] if c not in state[eid]]

    if not available_chits:
        # Reset after all chits used
        state[eid] = []
        available_chits = emotions[eid]["chits"]

    chosen = random.choice(available_chits)
    state[eid].append(chosen)

    # Save state with UTF-8 encoding
    with open(STATE_FILE, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False)

    return jsonify({"chit": chosen})

if __name__ == "__main__":
    app.run(debug=True)
